all:
  hosts:
    master:
      ansible_host: 158.160.53.180
      ansible_user: rdbmw
    node1:
      ansible_host: 158.160.47.191
      ansible_user: rdbmw
    node2:
      ansible_host: 62.84.114.36
      ansible_user: rdbmw
    node3:
      ansible_host: 158.160.51.3
      ansible_user: rdbmw
    node4:
      ansible_host: 158.160.57.106
      ansible_user: rdbmw
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
